src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Carbon\Carbon;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="user")
 * @UniqueEntity("email")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("message")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email()
     * @Assert\NotBlank(message="email.validate.bd")
     * @Groups("message")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $age;

    /**
     * @ORM\OneToMany(targetEntity=Brand::class, mappedBy="user", orphanRemoval=true)
     */
    private $brand;


    /**
     * @ORM\ManyToMany(targetEntity=Payment::class, mappedBy="user")
     */
    private $payments;

    /**
     * @ORM\OneToMany(targetEntity=Influencer::class, mappedBy="user", orphanRemoval=true)
     */
    private $influencer;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAdmin;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="user")
     */
    private $comments;

    public function __construct()
    {
        $this->brand = new ArrayCollection();
        $this->payments = new ArrayCollection();
        $this->influencer = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        // $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAge(): ?\DateTimeInterface
    {
        return $this->age;
    }

    public function setAge(\DateTimeInterface $age): self
    {
        $this->age = $age;

        return $this;
    }

    /**
     * @return Collection|Brand[]
     */
    public function getBrand(): Collection
    {
        return $this->brand;
    }

    public function addBrand(Brand $brand): self
    {
        if (!$this->brand->contains($brand)) {
            $this->brand[] = $brand;
            $brand->setUser($this);
        }

        return $this;
    }

    public function removeBrand(Brand $brand): self
    {
        if ($this->brand->removeElement($brand)) {
            // set the owning side to null (unless already changed)
            if ($brand->getUser() === $this) {
                $brand->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Payment[]
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->addUser($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self
    {
        if ($this->payments->removeElement($payment)) {
            $payment->removeUser($this);
        }

        return $this;
    }

    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
        ));
    }

    public function unserialize($serialized)
    {

        list(
            $this->id,
            $this->email,
            $this->password,
        ) = unserialize($serialized);
    }

    public function __toString()
    {
        return (string) $this->id;
    }

    /**
     * @return Collection|Influencer[]
     */
    public function getInfluencer(): Collection
    {
        return $this->influencer;
    }

    public function addInfluencer(Influencer $influencer): self
    {
        if (!$this->influencer->contains($influencer)) {
            $this->influencer[] = $influencer;
            $influencer->setUser($this);
        }

        return $this;
    }

    public function removeInfluencer(Influencer $influencer): self
    {
        if ($this->influencer->removeElement($influencer)) {
            // set the owning side to null (unless already changed)
            if ($influencer->getUser() === $this) {
                $influencer->setUser(null);
            }
        }

        return $this;
    }

    public function getIsAdmin(): ?bool
    {
        return $this->isAdmin;
    }

    public function setIsAdmin(bool $isAdmin): self
    {
        $this->isAdmin = $isAdmin;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
}

app/src/Controller/RegisterController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Brand;
use App\Entity\Influencer;
use App\Form\RegisterType;
use App\Form\BrandType;
use App\Form\InfluencerType;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


/**
 * @Route("/register", name="register_")
 */
class RegisterController extends AbstractController
{

    private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    /**
     * @Route("/", name="index")
     * @param Request $request
     * @return Response
     */
    public function createAction(Request $request): Response
    {
        $user = new User();
        $brand = new Brand();
        $influencer = new Influencer();
        $formU = $this->createForm(RegisterType::class, $user);
        $formB = $this->createForm(BrandType::class, $brand);
        $formI = $this->createForm(InfluencerType::class, $influencer);
        $formU->handleRequest($request);
        $formB->handleRequest($request);
        $formI->handleRequest($request);
        $userLogged = $this->getUser();

        if ($userLogged) {
            return $this->redirectToRoute('users_data');
        }

        if ($formU->isSubmitted() && $formU->isValid()) {
            $user->setPassword($this->passwordEncoder->encodePassword($user, $user->getPassword()));

            if (array_search("ROLE_INFLUENCEUR", $user->getRoles()) !== false) {
                $this->createInfluencerAction($request, $user);
            } 
            if (array_search("ROLE_MARQUE", $user->getRoles()) !== false) {
                $this->createBrandAction($request, $user);
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash("success", "Inscription réussie !");
            return $this->redirectToRoute('app_login');
        }
        // afficher le formulaire s'il n'est pas déjà rempli
        return $this->render('register/index.html.twig', [
            'formUser' => $formU->createView(),
            'formBrand' => $formB->createView(),
            'formInfluencer' => $formI->createView()
        ]);
    }
    private function createInfluencerAction($request, $user)
        {
            $influencer = new Influencer();
            $influencer->setUserId($user);
            $influencer->setName('testdespuislecontroller');
            //--------------
            $formI = $this->createForm(InfluencerType::class, $influencer);
            $formI->handleRequest($request);
            //--------------
            $em = $this->getDoctrine()->getManager();
            $em->persist($influencer);
        }
    private function createBrandAction($request, $user)
        {
            $brand = new Brand();
            $brand->setUserId($user);
            $brand->setName('testdespuislecontroller');
            //--------------
            $formB = $this->createForm(BrandType::class, $brand);
            $formB->handleRequest($request);
            //--------------
            $em = $this->getDoctrine()->getManager();
            $em->persist($brand);
        }
}

src/Controller/RegisterController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Brand;
use App\Form\BrandType;
use App\Entity\Influencer;
use App\Form\RegisterType;
use App\Form\InfluencerType;
use App\Repository\BrandRepository;
use App\Repository\InfluencerRepository;
use App\Security\LoginFormAuthenticator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Notifier\Recipient\Recipient;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


/**
 * @Route("/inscription", name="register_")
 */
class RegisterController extends AbstractController
{

    private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    /**
     * @Route("/", name="index")
     * @param Request $request
     * @return Response
     */
    public function createAction(Request $request, EntityManagerInterface $manager, NotifierInterface $notifier, LoginFormAuthenticator $login, GuardAuthenticatorHandler $guard)
    {
        $user = new User();
        $form = $this->createForm(RegisterType::class, $user);
        $form->handleRequest($request);
        $userLogged = $this->getUser();

        if ($userLogged) {
            return $this->redirectToRoute('users_data');
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword($this->passwordEncoder->encodePassword($user, $user->getPassword()));

            if (array_search("ROLE_INFLUENCEUR", $user->getRoles()) !== false) {
                $influencer = new Influencer();
                $influencer->setUser($user);
                $em = $this->getDoctrine()->getManager();
                $em->persist($influencer);
            } else if (array_search("ROLE_MARQUE", $user->getRoles()) !== false) {
                $brand = new Brand();
                $brand->setUser($user);

                $em = $this->getDoctrine()->getManager();
                $em->persist($brand);
            }

            $userEmail = $user->getEmail();
            $notification = (new Notification('Confirmation d\'inscription', ['email']))
                ->content('Bienvenue ' . $user->getLastname() . ' chez LIKKEY et Merci pour votre confiance.');

            // user recoit le mail
            $recipient = new Recipient(
                $userEmail
            );
            // Send the notification to the recipient
            $notifier->send($notification, $recipient);


            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash("success", "Inscription réussie !");

            $guard->authenticateUserAndHandleSuccess($user, $request, $login, 'main');

            return $this->redirectToRoute('register_complete');
        }

        // afficher le formulaire s'il n'est pas déjà rempli
        return $this->render('register/index.html.twig', [
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/complete", name="complete")
     */
    public function complete(Request $request, EntityManagerInterface $em, InfluencerRepository $influencerRepository, BrandRepository $brandRepository)
    {
        $user = $this->getUser();

        $influcerInfos = $influencerRepository->findOneBy(['user' => $user]);
        $brandInfos = $brandRepository->findOneBy(['user' => $user]);


        if ($influcerInfos) {
            if ($influcerInfos->getName() !== null) {
                return $this->redirectToRoute('users_data');
            }
        }
        if ($brandInfos) {
            if ($brandInfos->getName() !== null) {
                return $this->redirectToRoute('users_data');
            }
        }
        if ($user !== null) {
            if ($user->getRoles() == ["ROLE_INFLUENCEUR"] ||   $user->getRoles()[0] == "ROLE_INFLUENCEUR") {
                $form = $this->createForm(InfluencerType::class, $influcerInfos);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    $em->flush();

                    return $this->redirectToRoute('users_data');
                }

                $formView = $form->createView();

                return $this->render('register/complete_influencer.html.twig', [
                    'formView' => $formView,
                ]);
            } else {
                $form = $this->createForm(BrandType::class, $brandInfos);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    $em->flush();

                    return $this->redirectToRoute('users_data');
                }
                $formView = $form->createView();

                return $this->render('register/complete_brand.html.twig', [
                    'formView' => $formView,
                ]);
            }

            return $this->redirectToRoute('users_data');
        }
    }
}

templates/register/complete_brand.html.twig
{% extends 'base-no-user.html.twig' %}

{% block title %}
	Likkey - Inscription Marque
{% endblock %}


{% block body %}
	<div class="bg-white">
		<div class="mx-auto ">
			<nav class="flex items-center justify-center" aria-label="Progress">
				<p class="text-sm font-medium">Étape 2 sur 2</p>
				<ol class="flex items-center ml-8 space-x-5">

					<li>

						<a href="#" class="block w-2.5 h-2.5 bg-indigo-600 rounded-full hover:bg-indigo-900">
							<span class="sr-only">Étape 1</span>
						</a>
					</li>

					<li>

						<a href="#" class="relative flex items-center justify-center" aria-current="step">
							<span class="absolute flex w-5 h-5 p-px" aria-hidden="true">
								<span class="w-full h-full bg-indigo-200 rounded-full"></span>
							</span>
							<span class="relative block w-2.5 h-2.5 bg-indigo-600 rounded-full" aria-hidden="true"></span>
							<span class="sr-only">Step 2</span>
						</a>
					</li>
				</ol>
			</nav>
		</div>
	</div>
	<main class="pb-10 mx-auto max-w-7xl lg:py-12 lg:px-8">
		{% for message in app.flashes('error') %}
			<div class="col-xs4">
				<div class="p-3 my-2 rounded-2 error">{{message}}</div>
			</div>
		{% endfor %}

		<div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
			<section aria-labelledby="payment_details_heading">
				<div class="shadow sm:rounded-md sm:overflow-hidden">
					<div class="px-4 py-6 bg-white sm:p-6">
						{% for message in app.flashes('error') %}
							<div class="col-xs4">
								<div class="p-3 my-2 rounded-2 error">{{message}}</div>
							</div>
						{% endfor %}
						<h3>Mon profil</h3>

						{{ form_start(formView, {'multipart':'true'}) }}
						{{form_errors(formView)}}
						<div class="row">
							<div class="col">
								{{form_row(formView.name)}}
								{{form_row(formView.imageFile)}}
								{{form_row(formView.username)}}
								{{form_row(formView.description)}}
								{{form_row(formView.siret, { 'label': 'Siret (sans espaces)' })}} 
								{{form_row(formView.field)}}
							</div>
							<div class="col">
								{{form_row(formView.website)}}
								{{form_row(formView.instagram)}}
								{{form_row(formView.facebook)}}
								{{form_row(formView.youtube)}}
								{{form_row(formView.twitter)}}
								{{form_row(formView.twitch)}}
								{{form_row(formView.tiktok)}}
							</div>
						</div>

						<button type="submit" class="inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-indigo-500 rounded shadow ripple hover:shadow-lg hover:bg-indigo-600 focus:outline-none waves-effect">
							Sauvegarder</button>

						{{form_end(formView)}}
					</div>
				</section>
			</div>
		</div>
	</main>
{% endblock %}
{% block javascripts %}
	{{parent()}}
	<script>
		$.fn.previewImage = function () {
$(this).change(function (e) {
var url = URL.createObjectURL(e.target.files[0]);
$(this).parents('.vich-image').children('img').remove();
$(this).parents('.vich-image').prepend('<img class="preview_image" src="' + url + '"/>');
})
}
$('#brand_imageFile_file').previewImage();
$('#brand_imageFile_file').previewImage();
	</script>
{% endblock %}

templates/register/complete_influencer.html.twig
{% extends 'base-no-user.html.twig' %}

{% block title %}
	Likkey - Inscription influenceur
{% endblock %}


{% block body %}
	<div class="bg-white">
		<div class="mx-auto ">
			<nav class="flex items-center justify-center" aria-label="Progress">
				<p class="text-sm font-medium">Étape 2 sur 2</p>
				<ol class="flex items-center ml-8 space-x-5">

					<li>

						<a href="#" class="block w-2.5 h-2.5 bg-indigo-600 rounded-full hover:bg-indigo-900">
							<span class="sr-only">Étape 1</span>
						</a>
					</li>

					<li>

						<a href="#" class="relative flex items-center justify-center" aria-current="step">
							<span class="absolute flex w-5 h-5 p-px" aria-hidden="true">
								<span class="w-full h-full bg-indigo-200 rounded-full"></span>
							</span>
							<span class="relative block w-2.5 h-2.5 bg-indigo-600 rounded-full" aria-hidden="true"></span>
							<span class="sr-only">Step 2</span>
						</a>
					</li>
				</ol>
			</nav>
		</div>
	</div>
	<main class="pb-10 mx-auto max-w-7xl lg:py-12 lg:px-8">
		{% for message in app.flashes('error') %}
			<div class="col-xs4">
				<div class="p-3 my-2 rounded-2 error">{{message}}</div>
			</div>
		{% endfor %}

		<div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-9">
			<div class="shadow sm:rounded-md sm:overflow-hidden">
				<div class="px-4 py-6 bg-white sm:p-6">
					{% for message in app.flashes('error') %}
						<div class="col-xs4">
							<div class="p-3 my-2 rounded-2 error">{{message}}</div>
						</div>
					{% endfor %}
					<h3>Mon profil</h3>
					{{ form_start(formView, {'multipart':'true'}) }}
					{{form_errors(formView)}}
					<div class="row">
						<div class="col">
							{{form_row(formView.name)}}
							{{form_row(formView.imageFile)}}
							{{form_row(formView.username)}}
							{{form_row(formView.description)}}
							{{form_row(formView.siret)}}
							{{form_row(formView.type)}}
						</div>
						<div class="col">
							{{form_row(formView.website)}}
							{{form_row(formView.instagram)}}
							{{form_row(formView.facebook)}}
							{{form_row(formView.youtube)}}
							{{form_row(formView.twitter)}}
							{{form_row(formView.twitch)}}
							{{form_row(formView.tiktok)}}
						</div>
					</div>

					<button type="submit" class="inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-indigo-500 rounded shadow ripple hover:shadow-lg hover:bg-indigo-600 focus:outline-none waves-effect">
						Sauvegarder</button>

					{{form_end(formView)}}

				</div>
			</div>
		</main>

	{% endblock %}
	{% block javascripts %}
		{{parent()}}
		<script>
			$.fn.previewImage = function () {
$(this).change(function (e) {
var url = URL.createObjectURL(e.target.files[0]);
$(this).parents('.vich-image').children('img').remove();
$(this).parents('.vich-image').prepend('<img class="preview_image" src="' + url + '"/>');
})
}
$('#influencer_imageFile_file').previewImage();
$('#influencer_imageFile_file').previewImage();
		</script>
	{% endblock %}

templates/register/index.html.twig
{% extends 'base-no-user.html.twig' %}

{% block title %}
	Likkey - Inscription
{% endblock %}


{% block body %}
	<div class="bg-white"></div>
	<div class="pb-10 mx-auto">
		<nav class="flex items-center justify-center" aria-label="Progress">
			<p class="text-sm font-medium">Étape 1 sur 2</p>
			<ol class="flex items-center ml-8 space-x-5">


				<li>

					<a href="#" class="relative flex items-center justify-center" aria-current="step">
						<span class="absolute flex w-5 h-5 p-px" aria-hidden="true">
							<span class="w-full h-full bg-indigo-200 rounded-full"></span>
						</span>
						<span class="relative block w-2.5 h-2.5 bg-indigo-600 rounded-full" aria-hidden="true"></span>
						<span class="sr-only">Step 1</span>
					</a>
				</li>

				<li>

					<a href="#" class="block w-2.5 h-2.5 bg-gray-200 rounded-full hover:bg-gray-400">

						<span class="sr-only">Step 2</span>
					</a>
				</li>
			</ol>
		</nav>
	</div>
	<div class="p-5 mx-auto mb-5 rounded shadow card form-register">
		{{ form_start(form) }}
		<h3 class="mb-4">S'inscrire</h3>

		{{ form_widget(form) }}
		<button type="submit" class="inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-indigo-500 rounded shadow ripple hover:shadow-lg hover:bg-indigo-600 focus:outline-none waves-effect">Suivant</button>
		{{ form_end(form) }}

	</div>
{% endblock %}